### ISSUE TITLE
License Mismatch: PyPi vs. Repo

### ISSUE THREAD

**Issue by ryansb** [capless/envs#17]
On PyPi the license for this project is listed as GPLv3: [pypi](https://pypi.org/project/envs/) but the [setup.py](https://github.com/capless/envs/blob/master/setup.py#L15) file and [LICENSE](https://github.com/capless/envs/blob/master/LICENSE) both state Apache 2.0. 

Can you please update the PyPi metadata to match the actual license?

**Comment by mirzahbaig** [comment]
Same issue here. License scanning is rejecting whole library because of legacy license on pypi

**Comment by bjinwright** [comment]
Fixed
